name: Commit Building

on:
  push:
    branches: [ develop ]

jobs:
  test:
    name: Commit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v $(go list ./... | grep -v /test$| grep -v /cmd/webhook-hub$) -gcflags=all=-l
