name: Release-Pre

on:
  push:
    tags:
      - "v*.*.*-pre"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.0

      - name: Build linux-arm
        run: GOOS=linux GOARCH=arm go build -o webhook-hub-linux-arm cmd/webhook-hub/main.go
      - name: Compress & Package linux-arm
        run: tar -czvf webhook-hub-linux-arm.tar.gz webhook-hub-linux-arm

      - name: Build linux-arm64
        run: GOOS=linux GOARCH=arm64 go build -o webhook-hub-linux-arm64 cmd/webhook-hub/main.go
      - name: Compress & Package linux-arm64
        run: tar -czvf webhook-hub-linux-arm64.tar.gz webhook-hub-linux-arm64

      - name: Build linux-386
        run: GOOS=linux GOARCH=386 go build -o webhook-hub-linux-386 cmd/webhook-hub/main.go
      - name: Compress & Package linux-386
        run: tar -czvf webhook-hub-linux-386.tar.gz webhook-hub-linux-386

      - name: Build linux-amd64
        run: GOOS=linux GOARCH=amd64 go build -o webhook-hub-linux-amd64 cmd/webhook-hub/main.go
      - name: Compress & Package linux-amd64
        run: tar -czvf webhook-hub-linux-amd64.tar.gz webhook-hub-linux-amd64

      - name: Build darwin-arm64
        run: GOOS=darwin GOARCH=arm64 go build -o webhook-hub-darwin-arm64 cmd/webhook-hub/main.go
      - name: Compress & Package darwin-arm64
        run: tar -czvf webhook-hub-darwin-arm64.tar.gz webhook-hub-darwin-arm64

      - name: Build darwin-amd64
        run: GOOS=darwin GOARCH=amd64 go build -o webhook-hub-darwin-amd64 cmd/webhook-hub/main.go
      - name: Compress & Package darwin-amd64
        run: tar -czvf webhook-hub-darwin-amd64.tar.gz webhook-hub-darwin-amd64

      - name: Build windows-arm
        run: GOOS=windows GOARCH=arm go build -o webhook-hub-windows-arm.exe cmd/webhook-hub/main.go
      - name: Compress & Package windows-arm
        run: zip webhook-hub-windows-arm.zip webhook-hub-windows-arm.exe

      - name: Build windows-arm64
        run: GOOS=windows GOARCH=arm64 go build -o webhook-hub-windows-arm64.exe cmd/webhook-hub/main.go
      - name: Compress & Package windows-arm64
        run: zip webhook-hub-windows-arm64.zip webhook-hub-windows-arm64.exe

      - name: Build windows-386
        run: GOOS=windows GOARCH=386 go build -o webhook-hub-windows-386.exe cmd/webhook-hub/main.go
      - name: Compress & Package windows-386
        run: zip webhook-hub-windows-386.zip webhook-hub-windows-386.exe

      - name: Build windows-amd64
        run: GOOS=windows GOARCH=amd64 go build -o webhook-hub-windows-amd64.exe cmd/webhook-hub/main.go
      - name: Compress & Package windows-amd64
        run: zip webhook-hub-windows-amd64.zip webhook-hub-windows-amd64.exe

      - name: List
        run: ls -al
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            webhook-hub-linux-arm.tar.gz
            webhook-hub-linux-arm64.tar.gz
            webhook-hub-linux-386.tar.gz
            webhook-hub-linux-amd64.tar.gz
            webhook-hub-darwin-arm64.tar.gz
            webhook-hub-darwin-amd64.tar.gz
            webhook-hub-windows-arm.zip
            webhook-hub-windows-arm64.zip
            webhook-hub-windows-386.zip
            webhook-hub-windows-amd64.zip
            LICENSE
          body_path: CHANGELOG.txt
